services:
  db:
    container_name: db
    image: pgrouting/pgrouting:16-3.4-3.6.1
    restart: always
    environment:
      POSTGRES_PASSWORD: kj2aBv6f33cZ
    ports:
    - 5432:5432

  sistema:
    container_name: sistema
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './amenazas:/app/amenazas'
      - './infraestructura:/app/infraestructura'
      - './metadata:/app/metadata'
      - './sitio_web:/app/sitio_web'
      - './sql:/app/sql'
    restart: always
    environment:
      PGPASSWORD: kj2aBv6f33cZ
    depends_on:
    - db