services:
  db:
    container_name: db
    image: pgrouting/pgrouting:16-3.4-3.6.1
    restart: always
    environment:
      POSTGRES_PASSWORD: kj2aBv6f33cZ
    ports:
      - 5432:5432

  sistema:
    container_name: sistema
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './amenazas:/app/amenazas'
      - './infraestructura:/app/infraestructura'
      - './metadata:/app/metadata'
      - './sitio_web:/app/sitio_web'
      - './sql:/app/sql'
    restart: unless-stopped
    environment:
      PGPASSWORD: kj2aBv6f33cZ
    ports:
      - 5000:5000
    depends_on:
      - db

  geoserver:
    image: docker.osgeo.org/geoserver:2.26.0
    container_name: geoserver
    restart: always
    ports:
      - 8080:8080
    volumes:
      - './private/geoserver_data:/opt/geoserver_data'
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - ROOT_WEBAPP_REDIRECT=true
      - SKIP_DEMO_DATA=true
      - ENABLE_JSONP=true
    depends_on:
      - db