services:
  db:
    container_name: postgis
    image: postgis/postgis:16-master
    restart: always
    environment:
      POSTGRES_PASSWORD: kj2aBv6f33cZ
    ports:
    - 5432:5432

  sistema:
    container_name: sistema
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './amenazas:/app/amenazas'
      - './infraestructura:/app/infraestructura'
      - './metadata:/app/metadata'
      - './sitio_web:/app/sitio_web'
      - './sql:/app/sql'
    restart: always
    command: tail -F anything
    depends_on:
    - db